Import('file_env')

Import("""
    googlemock_lib
    googletest_lib
    file_lib
    platform
    libxml2_lib
""")

src_files = ['unittest_main.cpp']
src_files += Glob('../../OPCFileFormat/test/*.cpp')

libs = [
    googlemock_lib,
    googletest_lib,
    file_lib,
    libxml2_lib,
]

if platform == 'linux2':
    libs += [
        'pthread',
    ]

file_sdk_unittest_obj = file_env.Object(source = src_files);
file_sdk_unittest_exe = file_env.Program("file_sdk_unittest", source = file_sdk_unittest_obj, LIBS = [libs])
Return('file_sdk_unittest_exe')
