from build_config import *

Import("""
    crypto_platform_env
    platform
""")

src_files = ['base64.cpp']

if platform == 'win32':
  crypto_platform_env.Append(CPPPATH='#sdk/rmscrypto_sdk/')
  src_files += [
      'KeyStorageWindows.cpp',
      'sqlite3.c',
      'StorageAccessWindows.cpp',
  ]
elif platform == '__linux__':
  # CONFIG += link_pkgconfig
  # PKGCONFIG += glib-2.0
  crypto_platform_env.Append(CPPPATH='/usr/include/glib-2.0/')
  crypto_platform_env.Append(CPPPATH='/usr/include/libsecret-1/')
  crypto_platform_env.Append(CPPPATH='/usr/lib/x86_64-linux-gnu/glib-2.0/include/')
  src_files += ['KeyStoragePosix.cpp']  
elif platform == 'darwin':
  src_files += ['KeyStorageOSX.cpp']

# unix {
#     target.path = /usr/lib
#     INSTALLS += target
# }

crypto_platform_keystorage_obj = create_objs(crypto_platform_env, src_files)

Return('crypto_platform_keystorage_obj')