Import('rms_env qt_lib_path lib_suffix')

src_files = Glob('*.cpp')

libs = [
  'Qt5Core' + lib_suffix,
]

platform_logger_lib = rms_env.Library(target = "rms_platform_logger", \
    source = src_files, LIBS=libs, LIBPATH = qt_lib_path)
Return('platform_logger_lib')