from build_config import *

Import('rms_env qt_lib_path lib_suffix')

src_files = Glob('*.cpp')

libs = [
  'Qt5Core' + lib_suffix,
]

platform_json_lib = create_objs(rms_env, src_files)
# platform_json_lib = rms_env.Library(target = "rms_platform_json", \
    # source = src_files, LIBS = libs, LIBPATH = qt_lib_path)
Return('platform_json_lib')