//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureSenderLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureSenderLibrary.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued to $1 by $2.
        /// </summary>
        internal static string certificate_info_details {
            get {
                return ResourceManager.GetString("certificate_info_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Information.
        /// </summary>
        internal static string certificate_info_title {
            get {
                return ResourceManager.GetString("certificate_info_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4a63455a-cfa1-4ac6-bd2e-0d046cf1c3f7.
        /// </summary>
        internal static string client_id {
            get {
                return ResourceManager.GetString("client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The digital signature attached to this email doesn&apos;t match the contents of the email..
        /// </summary>
        internal static string doesnt_match_email_error_detail {
            get {
                return ResourceManager.GetString("doesnt_match_email_error_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error description.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The digital certificate attached to this email was not recognized by the RMS server..
        /// </summary>
        internal static string failed_server_validation_error {
            get {
                return ResourceManager.GetString("failed_server_validation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash_algorithm.
        /// </summary>
        internal static string hash_algorithm_key {
            get {
                return ResourceManager.GetString("hash_algorithm_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap invalid_email_icon {
            get {
                object obj = ResourceManager.GetObject("invalid_email_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no digital certificate attached to this email..
        /// </summary>
        internal static string malformed_error {
            get {
                return ResourceManager.GetString("malformed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-azure-secure-sender.
        /// </summary>
        internal static string mime_header {
            get {
                return ResourceManager.GetString("mime_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Property.
        /// </summary>
        internal static string properties_table_key_header {
            get {
                return ResourceManager.GetString("properties_table_key_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Status.
        /// </summary>
        internal static string properties_table_value_header {
            get {
                return ResourceManager.GetString("properties_table_value_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Validation.
        /// </summary>
        internal static string property_failed_verification_text {
            get {
                return ResourceManager.GetString("property_failed_verification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated Successfully.
        /// </summary>
        internal static string property_verified_text {
            get {
                return ResourceManager.GetString("property_verified_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occured. Please contact your system administrator.
        /// </summary>
        internal static string unspecified_error {
            get {
                return ResourceManager.GetString("unspecified_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email could not be verified by Azure Secure Sender.
        /// </summary>
        internal static string unverified_title {
            get {
                return ResourceManager.GetString("unverified_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been verified by Azure Secure Sender.
        /// </summary>
        internal static string verified_title {
            get {
                return ResourceManager.GetString("verified_title", resourceCulture);
            }
        }
    }
}
