from build_config import *

Import('rms_env platform qt_lib_path lib_suffix')

src_files = Glob('*.cpp')

for key in ['INCLUDE','LIB']:
    if os.environ.has_key(key):
        rms_env.Prepend(ENV = {key.upper():os.environ[key]})

if platform == 'win32':
  lib_path = [
      '#third_party/lib',
  ]
  libs = [
      'Qt5Core' + lib_suffix,
      'Qt5Network' + lib_suffix,
  ]

platform_http_lib = create_objs(rms_env, src_files)
# platform_http_lib = rms_env.Library(target = "rms_platform_http", \
    # source = src_files, LIBS=libs, LIBPATH = qt_lib_path)
Return('platform_http_lib')