from build_config import *

Import("""    
    platform
    file_env
""")

Import('file_env')

opc_env = file_env.Clone()

src_files = Glob('*.cpp')
src_files += Glob('xml/*.cpp')


if platform == 'win32':
    opc_env.Append(CPPPATH='#third_party/include/Libgsf')
else:
    opc_env.ParseConfig('pkg-config --cflags --libs libgsf-1')

opc_obj = create_objs(opc_env, src_files)
Return('opc_obj')