from build_config import *

Import('env bins')

variant_dir = '#' +  bins + '/sdk/file_sdk'

file_env = env.Clone()
file_env.Append(CPPPATH = ['#sdk/file_sdk'])

Export('file_env')

common_obj = file_env.SConscript('Common/SConscript', variant_dir = variant_dir + '/Common', duplicate=0)
Export('common_obj')

compound_obj = file_env.SConscript('CompoundFileFormat/SConscript', variant_dir = variant_dir + '/CompoundFileFormat', duplicate=0)
Export('compound_obj')

default_obj = file_env.SConscript('DefaultFormat/SConscript', variant_dir = variant_dir + '/DefaultFormat', duplicate=0)
Export('default_obj')

opc_obj = file_env.SConscript('OPCFileFormat/SConscript', variant_dir = variant_dir + '/OPCFileFormat', duplicate=0)
Export('opc_obj')

pdf_obj = file_env.SConscript('PDFFileFormat/SConscript', variant_dir = variant_dir + '/PDFFileFormat', duplicate=0)
Export('pdf_obj')

pfile_obj = file_env.SConscript('PFileFileFormat/SConscript', variant_dir = variant_dir + '/PFileFileFormat', duplicate=0)
Export('pfile_obj')

xmp_obj = file_env.SConscript('XMPFileFormat/SConscript', variant_dir = variant_dir + '/XMPFileFormat', duplicate=0)
Export('xmp_obj')

apiimpl_obj = file_env.SConscript('api_impl/SConscript', variant_dir = variant_dir + '/api_impl', duplicate=0)
Export('apiimpl_obj')

file_lib = file_env.SConscript('shared_lib/SConscript', variant_dir = '#' +  bins + '/sdk/shared_lib', duplicate=0)
Export('file_lib')

file_sdk_ut = file_env.SConscript('UnitTests/SConscript', duplicate=0)

Return('file_lib')