Import('rms_env qt_lib_path lib_suffix')

src_files = Glob('*.cpp')

rms_env.Append(CPPDEFINES = ['QT_NETWORK_LIB'])

rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

libs = [
  'Qt5Core' + lib_suffix,
]

platform_filesystem_lib = rms_env.Library(target = "rms_platform_filesystem", source = src_files, LIBS = libs, LIBPATH = qt_lib_path)
Return('platform_filesystem_lib')