from build_config import *

Import('rms_env')

src_files = Glob('*.cpp')

rms_env.Append(CPPDEFINES = ['QT_NETWORK_LIB'])

rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

platform_filesystem_obj = create_objs(rms_env, src_files)
Return('platform_filesystem_obj')