from build_config import create_objs

Import("""
    crypto_platform_crypto_lib
    lib_suffix
    qt_lib_path
    platform
    rmscrypto_env
""")

crypto_env = rmscrypto_env.Clone();
src_files = Glob('*.cpp')
if platform == 'win32':
  crypto_env.Append(CPPPATH='#third_party/include')
  
libs = [
  crypto_platform_crypto_lib,
]

libs += ['Qt5Core' + lib_suffix]

crypto_lib = create_objs(crypto_env, src_files)

# crypto_lib = crypto_env.Object(target = "crypto", source = src_files, LIBS = libs, LIBPATH = qt_lib_path)
Return('crypto_lib')