Import("""
    crypto_platform_crypto_lib
    lib_suffix
    qt_lib_path
    platform
    rmscrypto_env
""")

rmscrypto_env.Append(CPPDEFINES = ['RMS_CRYPTO_LIBRARY'])

crypto_env = rmscrypto_env.Clone();
src_files = Glob('*.cpp')
if platform == 'win32':
  crypto_env.Append(CPPPATH='#third_party/include')
  
libs = [
  crypto_platform_crypto_lib,
]

libs += ['Qt5Core' + lib_suffix]

crypto_lib = crypto_env.Library(target = "crypto", source = src_files, LIBS = libs, LIBPATH = qt_lib_path)
Return('crypto_lib')