#ifndef FILEAPI_SDK_GLOBAL_H
#define FILEAPI_SDK_GLOBAL_H

#if defined(FILEAPI_SDK_LIBRARY)
#  define FILEAPI_SDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEAPI_SDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEAPI_SDK_GLOBAL_H
