from build_config import *

Import('rms_env')

src_files = Glob('*.cpp')
rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')
rms_env.Append(CPPPATH='#sdk/rms_sdk/Common')
rms_env.Append(CPPPATH='#sdk/rms_sdk/Core')
rms_env.Append(CPPPATH='#sdk/rms_sdk/Platform/Logger')
rms_env.Append(CPPPATH='#sdk/rms_sdk/ModernAPI')
rms_env.Append(CPPPATH='#sdk/rms_sdk/FileAPI')

pfile_obj = create_objs(rms_env, src_files)
Return('pfile_obj')