Import('rms_env qt_lib_path lib_suffix')

src_files = Glob('*.cpp')
rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

libs = ['Qt5Core' + lib_suffix,]

pfile_lib = rms_env.Library(target = "pfile", source = src_files, LIBS = libs, LIBPPATH = qt_lib_path)
Return('pfile_lib')