Import('rms_env')

src_files = Split("""
	src/gmock-all.cc
""")
rms_env.Append(CPPPATH='#src/external/googlemock')
rms_env.Append(CPPPATH='#src/external/googletest')
rms_env.Append(CPPPATH='#src/external/googlemock/include')
rms_env.Append(CPPPATH='#src/external/googletest/include')
googlemock_lib = rms_env.Library(target = "googlemock", source = src_files)
Return('googlemock_lib')
