from build_config import *

Import('rmscrypto_env bins')

rmscrypto_env.Append(CPPDEFINES = ['QTFRAMEWORK'])
rmscrypto_env.Append(CPPDEFINES=['RMS_CRYPTO_LIBRARY'])

platform_obj = rmscrypto_env.SConscript('Platform/SConscript', duplicate=0)

crypto_obj = rmscrypto_env.SConscript('Crypto/SConscript', duplicate=0)
Export('crypto_obj')

crypto_api_obj = rmscrypto_env.SConscript('CryptoAPI/SConscript', duplicate=0)
Export('crypto_api_obj')

unittests_exe = rmscrypto_env.SConscript('UnitTests/SConscript', duplicate=0)
Export('unittests_exe')
Install('#' + bins + '/sdk/rmscrypto_sdk', unittests_exe)