from build_config import *

Import('rms_env')

src_files = Glob('*.cpp')

consent_lib = create_objs(rms_env, src_files)
# consent_lib = rms_env.Library(target = "consent", source = src_files)
Return('consent_lib')