import os.path
from build_config import *

Import("""
    lib_suffix
    platform
    qt_lib_path
    rms_env
""")

Import("""    
    crypto_lib
    crypto_api_lib
    crypto_platform_keystorage_lib
    crypto_platform_crypto_lib
    crypto_platform_logger_lib
    crypto_platform_settings_lib
    googletest_lib
    modernapi_lib
    rms_platform_filesystem_lib
    rms_platform_http_lib
    rms_platform_json_lib
    rms_platform_logger_lib
    rms_platform_settings_lib
    rms_platform_xml_lib
""")

src_files = Glob('*.cpp')
src_files += Glob('debug/*.cpp')

rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

srcdir = Dir('.').srcnode().abspath.replace('\\','/')

if platform == 'win32':
  rms_env.Append(CPPPATH='#third_party/include')
  rms_env.Append(CPPPATH='#googletest/include')
  rms_env.Replace(CCFLAGS=Split('-DSRCDIR=\\\"'+srcdir+'/\\\" -DUNICODE -DWIN64 -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB'))
  rms_env.Append(CCFLAGS=Split('-nologo -Zc:wchar_t -FS -Zc:strictStrings -Zi -MDd -W3 -w44456 -w44457 -w44458'))
  rms_env.Replace(CXXFLAGS=Split('-DUNICODE -DWIN64 -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB'))
  rms_env.Append(CXXFLAGS=Split('-c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc'))
  rms_env.Replace(LINKFLAGS=Split('/NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE'))
elif platform == '__linux__':
  rms_env.Append(CPPPATH='/usr/include/glib-2.0/')
  rms_env.Append(CPPPATH='/usr/include/libsecret-1/')
  rms_env.Append(CPPPATH='/usr/lib/x86_64-linux-gnu/glib-2.0/include/')

libs = [
      crypto_api_lib,
      crypto_lib,
      crypto_platform_keystorage_lib,
      crypto_platform_crypto_lib,
      crypto_platform_logger_lib,
      crypto_platform_settings_lib,   
      googletest_lib,
      modernapi_lib,
      rms_platform_filesystem_lib,
      rms_platform_http_lib,
      rms_platform_json_lib,
      rms_platform_logger_lib,
      rms_platform_settings_lib,
      rms_platform_xml_lib,      
]
if platform == 'win32':
  lib_path = [
      qt_lib_path, 
      '#third_party/lib/eay',
  ]
  rms_env.Replace(LIBPATH=lib_path)
  libs += [
      'Qt5Core' + lib_suffix,
      'Qt5Test' + lib_suffix,
      'Qt5Network' + lib_suffix,
      'Qt5Xml' + lib_suffix,
      'Qt5XmlPatterns' + lib_suffix,
      'libeay32',
      'ssleay32',
      'Advapi32',
      'Gdi32',
      'User32',
  ]
else:
  libs += 'ssl'
  libs += 'crypto'

platform_ut_obj = rms_env.Object(source = src_files)
platform_ut_test = rms_env.Program(target = "platform_ut", \
    source = [platform_ut_obj], LIBS = [libs], LIBPATH = lib_path)
Return('platform_ut_test')