from build_config import *

# platform_common_lib
Import("""
    rms_env
    crypto_lib
    crypto_api_lib
    platform
    modernapi_lib
    qt_lib_path
    rms_platform_filesystem_lib
    rms_platform_http_lib
    rms_platform_json_lib
    rms_platform_logger_lib
    rms_platform_settings_lib
    rms_platform_xml_lib
    crypto_platform_keystorage_lib
    crypto_platform_crypto_lib
    crypto_platform_logger_lib
    crypto_platform_settings_lib
    googletest_lib
""")

# rms_env = rms_env.Clone()
src_files = Glob('*.cpp')
src_files += Glob('debug/*.cpp')

rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

srcdir = "\\\"E:/rms-sdk-for-cpp/sdk/rms_sdk/UnitTests/platform_ut/\\\""

rms_env.Append(CPPDEFINES = { 'SRCDIR' : srcdir })

if platform == 'win32':
  rms_env.Append(CPPPATH='#third_party/include')
  rms_env.Append(CPPPATH='#googletest/include')
  rms_env.Replace(CCFLAGS=Split('-DSRCDIR=\\\"E:/rms-sdk-for-cpp/sdk/rms_sdk/UnitTests/platform_ut/\\\" -DUNICODE -DWIN64 -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB'))
  rms_env.Append(CCFLAGS=Split('-nologo -Zc:wchar_t -FS -Zc:strictStrings -Zi -MDd -W3 -w44456 -w44457 -w44458'))
  rms_env.Replace(CXXFLAGS=Split('-DUNICODE -DWIN64 -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB'))
  rms_env.Append(CXXFLAGS=Split('-c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MDd -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc'))
  rms_env.Replace(LINKFLAGS=Split('/NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE'))
elif platform == '__linux__':
  rms_env.Append(CPPPATH='/usr/include/glib-2.0/')
  rms_env.Append(CPPPATH='/usr/include/libsecret-1/')
  rms_env.Append(CPPPATH='/usr/lib/x86_64-linux-gnu/glib-2.0/include/')

libs = [
      crypto_lib,
      crypto_api_lib,
      modernapi_lib,
      rms_platform_filesystem_lib,
      rms_platform_http_lib,
      rms_platform_json_lib,
      rms_platform_logger_lib,
      rms_platform_settings_lib,
      rms_platform_xml_lib,
      crypto_platform_keystorage_lib,
      crypto_platform_crypto_lib,
      crypto_platform_logger_lib,
      crypto_platform_settings_lib,   
      googletest_lib,
]
if platform == 'win32':
  lib_path = [
      qt_lib_path, 
      '#third_party/lib/eay',
      '#bin/Debug/amd64/sdk/rms_sdk',
      '#bin/Debug/amd64/sdk/rmscrypto_sdk',
  ]
  rms_env.Replace(LIBPATH=lib_path)
  libs += [
      'Qt5Cored',
      'Qt5Testd',
      'Qt5Networkd',
      'Qt5Xmld',
      'Qt5XmlPatternsd',
      'libeay32',
      'ssleay32',
      'Advapi32',
      'Gdi32',
      'User32',
  ]
else:
  libs += 'ssl'
  libs += 'crypto'

platform_ut_obj = rms_env.Object(source = src_files)
platform_ut_test = rms_env.Program(target = "platform_ut", source = [platform_ut_obj], LIBS=[libs], LIBPATH=lib_path)
Return('platform_ut_test')