from build_config import *

Import("""    
    platform
    file_env
""")

Import('file_env')

src_files = Glob('*.cpp')

common_env = file_env.Clone()

if platform == 'win32':
    common_env.Append(CPPPATH='#third_party/include/Libgsf')
else:
    common_env.ParseConfig('pkg-config --cflags --libs libgsf-1')
	
common_obj = create_objs(common_env, src_files)
Return('common_obj')