from build_config import *

Import("""
    configuration
    crypto_lib
    crypto_platform_keystorage_lib
    crypto_platform_crypto_lib
    crypto_platform_logger_lib
    crypto_platform_settings_lib
    crypto_api_lib
    lib_suffix
    platform
    qt_lib_path
    rmscrypto_env
""")

src_files = Glob('*.cpp')
src_files += Glob(configuration + '/*.cpp')

libs = [
    crypto_api_lib,
    crypto_lib,
    crypto_platform_crypto_lib,
    crypto_platform_keystorage_lib,
    crypto_platform_logger_lib,
    crypto_platform_settings_lib,
    'Qt5Core' + lib_suffix,
    'Qt5Test' + lib_suffix,
    'Qt5Widgets' + lib_suffix,
    'Qt5Gui' + lib_suffix,
] 
lib_path = [
    qt_lib_path,
]

rmscrypto_ut_env =  rmscrypto_env.Clone()
srcdir = "\\\"" + Dir('.').srcnode().abspath + "/\\\""

rmscrypto_ut_env.Append(CPPDEFINES = { 'SRCDIR' : srcdir })
rmscrypto_ut_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

if platform == 'win32':
  rmscrypto_ut_env.Append(CCFLAGS=Split('-DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB'))
  rmscrypto_ut_env.Append(CXXFLAGS=Split('-DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB'))
  rmscrypto_ut_env.Append(LINKFLAGS=Split('/NOLOGO /DYNAMICBASE /NXCOMPAT /SUBSYSTEM:CONSOLE'))
  if configuration == 'debug':
    rmscrypto_ut_env.Append(LINKFLAGS=Split('/DEBUG'))
  elif configuration == 'release':
    rmscrypto_ut_env.Append(LINKFLAGS=Split('/INCREMENTAL:NO'))
  rmscrypto_ut_env.Append(CPPPATH='#third_party/include')
  libs += [
    'libeay32',
    'ssleay32',
    'Advapi32',
    'Gdi32',
    'User32',
  ]
  lib_path += [
      '#third_party/lib/eay',
  ]
elif platform == '__linux__':
  rmscrypto_ut_env.Append(CPPPATH='/usr/include/glib-2.0/')
  rmscrypto_ut_env.Append(CPPPATH='/usr/include/libsecret-1/')
  rmscrypto_ut_env.Append(CPPPATH='/usr/lib/x86_64-linux-gnu/glib-2.0/include/')
  libs +=[
      'ssl'
      'crypto'
      'secret-1'
      'glib-2.0'
  ]
elif platform == 'darwin':
  libs +=[
      'ssl'
      'crypto'
  ]

rmscrypto_ut_obj = rmscrypto_ut_env.Object(source = src_files)
unittests_lib = rmscrypto_ut_env.Program(target = "unittests", source=[rmscrypto_ut_obj], LIBS = [libs], LIBPATH=lib_path)
Return('unittests_lib')