Import('file_env bins')

variant_dir = '#' +  bins + '/sdk/file_sdk/unittests/'

#common_ut_lib = file_env.SConscript('common_ut/SConscript', variant_dir=variant_dir + 'common', duplicate=0)

file_sdk_ut = file_env.SConscript('gtest/SConscript', variant_dir=variant_dir + 'gtest', duplicate=0)
Install("#" + bins + '/sdk/file_sdk', file_sdk_ut)