Import('file_env bins')

variant_dir = '#' +  bins + '/sdk/file_sdk/unittests/'

file_sdk_ut = file_env.SConscript('gtest/SConscript', variant_dir=variant_dir + 'gtest', duplicate=0)
Install("#" + bins + '/sdk/file_sdk', file_sdk_ut)