from build_config import create_objs

Import("""
    build_arch
    configuration
    crypto_lib
    crypto_api_obj_files
    crypto_platform_crypto_lib
    rmscrypto_env
    crypto_platform_keystorage_lib
    crypto_platform_logger_lib
    crypto_platform_settings_lib
    lib_suffix
    qt_lib_path
    platform
""")

rmscryptodll_env = rmscrypto_env.Clone()

# src_files = Glob('#sdk\rmscrypto_sdk\CryptoAPI\*.cpp')


libs = [
  crypto_lib,
  crypto_platform_keystorage_lib,
  crypto_platform_crypto_lib,
  crypto_platform_logger_lib,
  crypto_platform_settings_lib,
]

if platform == 'win32':
  rmscryptodll_env.Append(CPPPATH='#third_party/include')
  # rmscryptodll_env.Append(CPPDEFINES=['RMS_CRYPTO_LIBRARY'])
  rmscryptodll_env.Replace(LINKFLAGS=Split('/DLL /MACHINE:'+build_arch+' /SUBSYSTEM:WINDOWS'))
  # rmscryptodll_env.Append(CCFLAGS=Split('-DQT_PLUGIN'))
  # rmscryptodll_env.Append(CXXFLAGS=Split('-DQT_PLUGIN'))
  if configuration == 'debug':
    rmscryptodll_env.Append(LINKFLAGS=Split('/DEBUG'))
  elif configuration == 'release':
    rmscryptodll_env.Append(LINKFLAGS=Split('/INCREMENTAL:NO'))
  lib_path = [
      qt_lib_path, 
      '#third_party/lib/eay',
  ]
  libs += [
      'Qt5Core' + lib_suffix,
      'libeay32',
      'ssleay32',
      'Advapi32',
      'Gdi32',
      'User32',
      'legacy_stdio_definitions',
  ]
elif platform == '__linux__':
  rmscryptodll_env.Append(CPPPATH='/usr/include/glib-2.0/')
  rmscryptodll_env.Append(CPPPATH='/usr/include/libsecret-1/')
  rmscryptodll_env.Append(CPPPATH='/usr/lib/x86_64-linux-gnu/glib-2.0/include/')
  libs += [
      'ssl'
      'crypto'
      'secret-1'
      'glib-2.0'
  ]
elif platform == 'darwin':
  libs += 'ssl'
  libs += 'crypto'

# unix {
#     contains(QMAKE_HOST.arch, x86_64) {
#         target.path = /usr/lib64
#         INSTALLS += target
#     } else {
#         target.path += /usr/lib
#         INSTALLS += target
#     }
# }

rmscrypto_lib = rmscryptodll_env.SharedLibrary(target = "rmscrypto", source = crypto_api_obj_files, LIBS = libs, LIBPATH = lib_path)
Return('rmscrypto_lib')