//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSecureSender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzureSecureSender.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Count.
        /// </summary>
        internal static string attachments_count_display_name {
            get {
                return ResourceManager.GetString("attachments_count_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachments_count.
        /// </summary>
        internal static string attachments_count_key {
            get {
                return ResourceManager.GetString("attachments_count_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment #.
        /// </summary>
        internal static string attachments_hash_display_name {
            get {
                return ResourceManager.GetString("attachments_hash_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment_.
        /// </summary>
        internal static string attachments_hash_key {
            get {
                return ResourceManager.GetString("attachments_hash_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Body.
        /// </summary>
        internal static string body_hash_display_name {
            get {
                return ResourceManager.GetString("body_hash_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        internal static string body_hash_key {
            get {
                return ResourceManager.GetString("body_hash_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed.
        /// </summary>
        internal static string email_properties_table_false_value {
            get {
                return ResourceManager.GetString("email_properties_table_false_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Property.
        /// </summary>
        internal static string email_properties_table_header_keys {
            get {
                return ResourceManager.GetString("email_properties_table_header_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated Status.
        /// </summary>
        internal static string email_properties_table_header_values {
            get {
                return ResourceManager.GetString("email_properties_table_header_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Successful.
        /// </summary>
        internal static string email_properties_table_true_value {
            get {
                return ResourceManager.GetString("email_properties_table_true_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing Algorithm.
        /// </summary>
        internal static string hash_algorithm_display_name {
            get {
                return ResourceManager.GetString("hash_algorithm_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash_algorithm.
        /// </summary>
        internal static string hash_algorithm_key {
            get {
                return ResourceManager.GetString("hash_algorithm_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Microsoft_logo_svg {
            get {
                object obj = ResourceManager.GetObject("Microsoft_logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-azure-secure-sender.
        /// </summary>
        internal static string mime_header {
            get {
                return ResourceManager.GetString("mime_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        internal static string sender_email_address_display_name {
            get {
                return ResourceManager.GetString("sender_email_address_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sender_email_address.
        /// </summary>
        internal static string sender_email_address_key {
            get {
                return ResourceManager.GetString("sender_email_address_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Line.
        /// </summary>
        internal static string subject_display_name {
            get {
                return ResourceManager.GetString("subject_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject_line.
        /// </summary>
        internal static string subject_key {
            get {
                return ResourceManager.GetString("subject_key", resourceCulture);
            }
        }
    }
}
