Import('rms_env')

rms_env.Append(CPPDEFINES = ['QTFRAMEWORK'])

src_files = Split("""
	src/gtest-all.cc
""")

googletest_lib = rms_env.Library(target = "googletest", source = src_files)
Return('googletest_lib')
