from build_config import *

Import('rms_env')

rms_env.Append(CPPDEFINES = ['QTFRAMEWORK'])

src_files = Split("""
	#googletest/src/gtest-all.cc
""")

googletest_obj = create_objs(rms_env, src_files)
Return('googletest_obj')
