Import('rms_env qt_lib_path lib_suffix')

src_files = Glob('*.cpp')
rms_env.Append(CPPPATH='#sdk/rmscrypto_sdk/CryptoAPI')

libs = [
  'Qt5Core' + lib_suffix,
  'Qt5Network' + lib_suffix,
  'Qt5Xml' + lib_suffix,
]

restclients_lib = rms_env.Library(target = "restclients", \
    source = src_files, LIBS = libs, LIBPATH = qt_lib_path)
Return('restclients_lib')