/*
 * ======================================================================
 * Copyright (c) Microsoft Open Technologies, Inc.  All rights reserved.
 * Licensed under the MIT License.
 * See LICENSE.md in the project root for license information.
 * ======================================================================
*/

#ifndef RMSSDK_PDFOBJECTMODEL_CORE_H_
#define RMSSDK_PDFOBJECTMODEL_CORE_H_

#include "fpdfapi/fpdf_module.h"
#include "fpdfapi/fpdf_objects.h"
#include "fxcodec/fx_codec.h"
#include "fpdfapi/fpdf_serial.h"
#include "fpdfdoc/fpdf_doc.h"
#include "fxcrt/fx_ext.h"
#include "fxcrt/fx_stream.h"
#include "fxcrt/fx_string.h"
#include "fxcrt/fx_basic.h"
#include "fxcrt/fx_system.h"

#endif // RMSSDK_PDFOBJECTMODEL_CORE_H_

