from build_config import *

Import("""
    platform     
    rms_env
""")

fileapi_env = rms_env.Clone()

fileapi_env.Append(CCFLAGS=Split('-DRMS_LIBRARY -DQT_NO_KEYWORDS'))
fileapi_env.Append(CXXFLAGS=Split('-DRMS_LIBRARY -DQT_NO_KEYWORDS'))

src_files = Glob('*.cpp')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/Platform/Logger')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/ModernAPI')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/OfficeProtector')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/PFile')

if platform == 'win32':
    fileapi_env.Append(CPPPATH='#third_party/include/Libgsf')
else:
    fileapi_env.ParseConfig('pkg-config --cflags --libs libgsf-1')

fileapi_obj = create_objs(fileapi_env, src_files)
Return('fileapi_obj')