from build_config import *

Import("""        
    rms_env
""")

fileapi_env = rms_env.Clone()

fileapi_env.Append(CCFLAGS=Split('-DRMS_LIBRARY -DQT_NO_KEYWORDS'))
fileapi_env.Append(CXXFLAGS=Split('-DRMS_LIBRARY -DQT_NO_KEYWORDS')

src_files = Glob('*.cpp')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/Platform/Logger')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/ModernAPI')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/OfficeProtector')
fileapi_env.Append(CPPPATH='#sdk/rms_sdk/PFile')

fileapi_obj = create_objs(fileapi_env, src_files)
Return('fileapi_obj')