Import('rms_env bins')

rms_env.Append(CCFLAGS=Split('-DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB'))
rms_env.Append(CXXFLAGS=Split('-DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB'))

platform_ut_lib = rms_env.SConscript('platform_ut/SConscript', duplicate=0)
rest_clients_ut_lib = rms_env.SConscript('rest_clients_ut/SConscript', duplicate=0)