from build_config import *

Import('rms_env bins')

platform_ut_lib = rms_env.SConscript('platform_ut/SConscript', duplicate=0)
rest_clients_ut_lib = rms_env.SConscript('rest_clients_ut/SConscript', duplicate=0)

# libs = [
#   platform_ut_lib,
#   rest_clients_ut_lib,
# ]

# rms_unittests_lib = env.SharedLibrary(target = "rms_unittests", LIBS = libs)

# Return('rms_unittests_lib')