from build_config import *

Import('env bins')

env.Append(CPPPATH='#sdk/rms_sdk/Profile')
variant_dir = '#' +  bins + '/sdk'

googletest_lib = env.SConscript('#googletest/SConscript', variant_dir='#' +  bins + '/googletest', duplicate=0)
googlemock_lib = env.SConscript('#googlemock/SConscript', variant_dir='#' +  bins + '/googlemock', duplicate=0)
Export('googletest_lib googlemock_lib')

rmscrypto_env = env.Clone()
rms_env = env.Clone()

Export('rmscrypto_env rms_env')

rmscrypto_sdk_lib = rmscrypto_env.SConscript('#sdk/rmscrypto_sdk/SConscript', variant_dir = variant_dir + '/rmscrypto_sdk', duplicate=0)
rms_sdk_lib = rms_env.SConscript('#sdk/rms_sdk/SConscript', variant_dir = variant_dir + '/rms_sdk', duplicate=0)

rms_lib, rmsfile_lib = env.SConscript('shared_lib/SConscript', duplicate=0)
file_lib = env.SConscript('#sdk/file_sdk/SConscript', duplicate=0)

Export('rms_lib rmsfile_lib file_lib')
Install('#' + bins + '/sdk', rms_lib)
Install('#' + bins + '/sdk', rmsfile_lib)
Install('#' + bins + '/sdk', file_lib)
