from build_config import *

Import('rms_env qt_lib_path')

# rms_env.Append(CPPDEFINES = ['QTFRAMEWORK'])

src_files = Glob('*.cpp')

libs = [
  'Qt5Xmld',
  'Qt5XmlPatternsd',
]

platform_xml_lib = rms_env.Library(target = "rms_platform_xml", source = src_files, LIBS = libs, LIBPATH=qt_lib_path)
Return('platform_xml_lib')