from build_config import *

Import('rms_env bins')

platform_objs = rms_env.SConscript('Platform/SConscript', duplicate=0)

common_obj = rms_env.SConscript('Common/SConscript', duplicate=0)
Export('common_obj')

consent_obj = rms_env.SConscript('Consent/SConscript', duplicate=0)
Export('consent_obj')

core_obj = rms_env.SConscript('Core/SConscript', duplicate=0)
Export('core_obj')

googletest_obj = rms_env.SConscript('GoogleTest/SConscript', duplicate=0)
Export('googletest_obj')

json_obj = rms_env.SConscript('Json/SConscript', duplicate=0)
Export('json_obj')

pfile_obj = rms_env.SConscript('PFile/SConscript', duplicate=0)
Export('pfile_obj')

office_obj = rms_env.SConscript('OfficeProtector/SConscript', duplicate=0)
Export('office_obj')

fileapi_obj = rms_env.SConscript('FileAPI/SConscript', duplicate=0)
Export('fileapi_obj')

restclients_obj = rms_env.SConscript('RestClients/SConscript', duplicate=0)
Export('restclients_obj')

modernapi_obj = rms_env.SConscript('ModernApi/SConscript', duplicate=0)
Export('modernapi_obj')

rms_platform_ut = rms_env.SConscript('UnitTests/platform_ut/SConscript', duplicate=0)
Export('rms_platform_ut')
Install('#' + bins + '/sdk/rms_sdk', rms_platform_ut)

rest_clients_ut = rms_env.SConscript('UnitTests/rest_clients_ut/SConscript', duplicate=0)
Export('rest_clients_ut')
Install('#' + bins + '/sdk/rms_sdk', rest_clients_ut)