from build_config import *

Import('rms_env bins')

rms_env.Append(CPPDEFINES = ['QTFRAMEWORK'])

rms_platform_filesystem_lib = rms_env.SConscript('Filesystem/SConscript', duplicate=0)
rms_platform_http_lib = rms_env.SConscript('Http/SConscript', duplicate=0)
rms_platform_json_lib = rms_env.SConscript('Json/SConscript', duplicate=0)
rms_platform_logger_lib = rms_env.SConscript('Logger/SConscript', duplicate=0)
rms_platform_settings_lib = rms_env.SConscript('Settings/SConscript', duplicate=0)
rms_platform_xml_lib = rms_env.SConscript('Xml/SConscript', duplicate=0)

Export("""
  rms_platform_filesystem_lib
  rms_platform_http_lib
  rms_platform_json_lib
  rms_platform_logger_lib
  rms_platform_settings_lib
  rms_platform_xml_lib
""")

Install('#' + bins + '/sdk/rms_sdk', rms_platform_filesystem_lib)
Install('#' + bins + '/sdk/rms_sdk', rms_platform_http_lib)
Install('#' + bins + '/sdk/rms_sdk', rms_platform_json_lib)
Install('#' + bins + '/sdk/rms_sdk', rms_platform_logger_lib)
Install('#' + bins + '/sdk/rms_sdk', rms_platform_settings_lib)
Install('#' + bins + '/sdk/rms_sdk', rms_platform_xml_lib)