from build_config import *

Import('rms_env bins')

rms_env.Append(CPPDEFINES = ['QTFRAMEWORK'])

rms_platform_filesystem_obj = rms_env.SConscript('Filesystem/SConscript', duplicate=0)
rms_platform_http_obj = rms_env.SConscript('Http/SConscript', duplicate=0)
rms_platform_json_obj = rms_env.SConscript('Json/SConscript', duplicate=0)
rms_platform_logger_obj = rms_env.SConscript('Logger/SConscript', duplicate=0)
rms_platform_settings_obj = rms_env.SConscript('Settings/SConscript', duplicate=0)
rms_platform_xml_obj = rms_env.SConscript('Xml/SConscript', duplicate=0)

Export("""
  rms_platform_filesystem_obj
  rms_platform_http_obj
  rms_platform_json_obj
  rms_platform_logger_obj
  rms_platform_settings_obj
  rms_platform_xml_obj
""")