from build_config import *

Import("""
    crypto_platform_env
""")

src_files = Glob('*.cpp')

crypto_platform_logger_obj = create_objs(crypto_platform_env, src_files)

Return('crypto_platform_logger_obj')